### ISSUE TITLE
how to set the setting.py

### ISSUE THREAD

**Issue by jianzhengming** [vladsandulescu/topics#5]
When I run the reviews.py, I was confused the setting.py and encountered some problems.
Can you give some introduction on how to set the setting.py.

**Comment by vladsandulescu** [comment]
Hi,

Sure.
In short, you just need to install MongoDB and most probably the MONGO_CONNECTION_STRING will not change for you. The only things you would need to change the path to actually is just the Yelp dataset file.
DATASET_FILE = The link to your Yelp dataset file
    MONGO_CONNECTION_STRING = The default Mongo connection string
    REVIEWS_DATABASE = Name of the MongoDB reviews database
    TAGS_DATABASE = Name of the MongoDB tags database
    REVIEWS_COLLECTION = Name of the MongoDB reviews collections
    CORPUS_COLLECTION = Name of the MongoDB corpus collection
